// 1. アメリカ50州（州都・旗画像入り）
const flagData = [
    { q: "アラバマ州", a: "モンゴメリー", img: "Flag_of_Alabama.svg" },
    { q: "アラスカ州", a: "ジュノー", img: "Flag_of_Alaska.svg" },
    { q: "アリゾナ州", a: "フェニックス", img: "Flag_of_Arizona.svg" },
    { q: "アーカンソー州", a: "リトルロック", img: "Flag_of_Arkansas.svg" },
    { q: "カリフォルニア州", a: "サクラメント", img: "Flag_of_California.svg" },
    { q: "コロラド州", a: "デンバー", img: "Flag_of_Colorado.svg" },
    { q: "コネチカット州", a: "ハートフォード", img: "Flag_of_Connecticut.svg" },
    { q: "デラウェア州", a: "ドーバー", img: "Flag_of_Delaware.svg" },
    { q: "フロリダ州", a: "タラハシー", img: "Flag_of_Florida.svg" },
    { q: "ジョージア州", a: "アトランタ", img: "Flag_of_Georgia.svg" },
    { q: "ハワイ州", a: "ホノルル", img: "Flag_of_Hawaii.svg" },
    { q: "アイダホ州", a: "ボイシ", img: "Flag_of_Idaho.svg" },
    { q: "イリノイ州", a: "スプリングフィールド", img: "Flag_of_Illinois.svg" },
    { q: "インディアナ州", a: "インディアナポリス", img: "Flag_of_Indiana.svg" },
    { q: "アイオワ州", a: "デモイン", img: "Flag_of_Iowa.svg" },
    { q: "カンザス州", a: "トピカ", img: "Flag_of_Kansas.svg" },
    { q: "ケンタッキー州", a: "フランクフォート", img: "Flag_of_Kentucky.svg" },
    { q: "ルイジアナ州", a: "バトンルージュ", img: "Flag_of_Louisiana.svg" },
    { q: "メイン州", a: "オーガスタ", img: "Flag_of_Maine.svg" },
    { q: "メリーランド州", a: "アナポリス", img: "Flag_of_Maryland.svg" },
    { q: "マサチューセッツ州", a: "ボストン", img: "Flag_of_Massachusetts.svg" },
    { q: "ミシガン州", a: "ランシング", img: "Flag_of_Michigan.svg" },
    { q: "ミネソタ州", a: "セントポール", img: "Flag_of_Minnesota.svg" },
    { q: "ミシシッピ州", a: "ジャクソン", img: "Flag_of_Mississippi.svg" },
    { q: "ミズーリ州", a: "ジェファーソンシティ", img: "Flag_of_Missouri.svg" },
    { q: "モンタナ州", a: "ヘレナ", img: "Flag_of_Montana.svg" },
    { q: "ネブラスカ州", a: "リンカーン", img: "Flag_of_Nebraska.svg" },
    { q: "ネバダ州", a: "カーソンシティ", img: "Flag_of_Nevada.svg" },
    { q: "ニューハンプシャー州", a: "コンコード", img: "Flag_of_New_Hampshire.svg" },
    { q: "ニュージャージー州", a: "トレントン", img: "Flag_of_New_Jersey.svg" },
    { q: "ニューメキシコ州", a: "サンタフェ", img: "Flag_of_New_Mexico.svg" },
    { q: "ニューヨーク州", a: "オールバニ", img: "Flag_of_New_York.svg" },
    { q: "ノースカロライナ州", a: "ローリー", img: "Flag_of_North_Carolina.svg" },
    { q: "ノースダコタ州", a: "ビスマーク", img: "Flag_of_North_Dakota.svg" },
    { q: "オハイオ州", a: "コロンバス", img: "Flag_of_Ohio.svg" },
    { q: "オクラホマ州", a: "オクラホマシティ", img: "Flag_of_Oklahoma.svg" },
    { q: "オレゴン州", a: "セイラム", img: "Flag_of_Oregon.svg" },
    { q: "ペンシルベニア州", a: "ハリスバーグ", img: "Flag_of_Pennsylvania.svg" },
    { q: "ロードアイランド州", a: "プロビデンス", img: "Flag_of_Rhode_Island.svg" },
    { q: "サウスカロライナ州", a: "コロンビア", img: "Flag_of_South_Carolina.svg" },
    { q: "サウスダコタ州", a: "ピア", img: "Flag_of_South_Dakota.svg" },
    { q: "テネシー州", a: "ナッシュビル", img: "Flag_of_Tennessee.svg" },
    { q: "テキサス州", a: "オースティン", img: "Flag_of_Texas.svg" },
    { q: "ユタ州", a: "ソルトレイクシティ", img: "Flag_of_Utah.svg" },
    { q: "バーモント州", a: "モンペリエ", img: "Flag_of_Vermont.svg" },
    { q: "バージニア州", a: "リッチモンド", img: "Flag_of_Virginia.svg" },
    { q: "ワシントン州", a: "オリンピア", img: "Flag_of_Washington.svg" },
    { q: "ウェストバージニア州", a: "チャールストン", img: "Flag_of_West_Virginia.svg" },
    { q: "ウィスコンシン州", a: "マディソン", img: "Flag_of_Wisconsin.svg" },
    { q: "ワイオミング州", a: "シャイアン", img: "Flag_of_Wyoming.svg" }
];

// 2. 全天88星座（完全88個・和名対応）
const constellationData = [
    { q: "アンドロメダ座", a: "アンドロメダ", img: "Andromeda_IAU.svg" },
    { q: "いっかくじゅう座", a: "いっかくじゅう", img: "Monoceros_IAU.svg" },
    { q: "いて座", a: "いて", img: "Sagittarius_IAU.svg" },
    { q: "いるか座", a: "いるか", img: "Delphinus_IAU.svg" },
    { q: "インディアン座", a: "インディアン", img: "Indus_IAU.svg" },
    { q: "うお座", a: "うお", img: "Pisces_IAU.svg" },
    { q: "うさぎ座", a: "うさぎ", img: "Lepus_IAU.svg" },
    { q: "うしかい座", a: "うしかい", img: "Bootes_IAU.svg" },
    { q: "うみへび座", a: "うみへび", img: "Hydra_IAU.svg" },
    { q: "えかき座", a: "えかき", img: "Pictor_IAU.svg" },
    { q: "エリダヌス座", a: "エリダヌス", img: "Eridanus_IAU.svg" },
    { q: "おうし座", a: "おうし", img: "Taurus_IAU.svg" },
    { q: "おおかみ座", a: "おおかみ", img: "Lupus_IAU.svg" },
    { q: "おおぐま座", a: "おおぐま", img: "Ursa_Major_IAU.svg" },
    { q: "おおいぬ座", a: "おおいぬ", img: "Canis_Major_IAU.svg" },
    { q: "おとめ座", a: "おとめ", img: "Virgo_IAU.svg" },
    { q: "おひつじ座", a: "おひつじ", img: "Aries_IAU.svg" },
    { q: "オリオン座", a: "オリオン", img: "Orion_IAU.svg" },
    { q: "かじき座", a: "かじき", img: "Dorado_IAU.svg" },
    { q: "カシオペヤ座", a: "カシオペヤ", img: "Cassiopeia_IAU.svg" },
    { q: "かに座", a: "かに", img: "Cancer_IAU.svg" },
    { q: "かみのけ座", a: "かみのけ", img: "Coma_Berenices_IAU.svg" },
    { q: "カメレオン座", a: "カメレオン", img: "Chamaeleon_IAU.svg" },
    { q: "からす座", a: "からす", img: "Corvus_IAU.svg" },
    { q: "かんむり座", a: "かんむり", img: "Corona_Borealis_IAU.svg" },
    { q: "きょしちょう座", a: "きょしちょう", img: "Tucana_IAU.svg" },
    { q: "ぎょしゃ座", a: "ぎょしゃ", img: "Auriga_IAU.svg" },
    { q: "きりん座", a: "きりん", img: "Camelopardalis_IAU.svg" },
    { q: "くじゃく座", a: "くじゃく", img: "Pavo_IAU.svg" },
    { q: "くじら座", a: "くじら", img: "Cetus_IAU.svg" },
    { q: "ケフェウス座", a: "ケフェウス", img: "Cepheus_IAU.svg" },
    { q: "ケンタウルス座", a: "ケンタウルス", img: "Centaurus_IAU.svg" },
    { q: "けんびきょう座", a: "けんびきょう", img: "Microscopium_IAU.svg" },
    { q: "こいぬ座", a: "こいぬ", img: "Canis_Minor_IAU.svg" },
    { q: "こうま座", a: "こうま", img: "Equuleus_IAU.svg" },
    { q: "こぎつね座", a: "こぎつね", img: "Vulpecula_IAU.svg" },
    { q: "こぐま座", a: "こぐま", img: "Ursa_Minor_IAU.svg" },
    { q: "こじし座", a: "こじし", img: "Leo_Minor_IAU.svg" },
    { q: "コップ座", a: "コップ", img: "Crater_IAU.svg" },
    { q: "こと座", a: "こと", img: "Lyra_IAU.svg" },
    { q: "コンパス座", a: "コンパス", img: "Circinus_IAU.svg" },
    { q: "さいだん座", a: "さいだん", img: "Ara_IAU.svg" },
    { q: "さそり座", a: "さそり", img: "Scorpius_IAU.svg" },
    { q: "さんかく座", a: "さんかく", img: "Triangulum_IAU.svg" },
    { q: "しし座", a: "しし", img: "Leo_IAU.svg" },
    { q: "じょうぎ座", a: "じょうぎ", img: "Norma_IAU.svg" },
    { q: "たて座", a: "たて", img: "Scutum_IAU.svg" },
    { q: "ちょうこくぐ座", a: "ちょうこくぐ", img: "Caelum_IAU.svg" },
    { q: "ちょうこくしつ座", a: "ちょうこくしつ", img: "Sculptor_IAU.svg" },
    { q: "つる座", a: "つる", img: "Grus_IAU.svg" },
    { q: "テーブルさん座", a: "テーブルさん", img: "Mensa_IAU.svg" },
    { q: "てんびん座", a: "てんびん", img: "Libra_IAU.svg" },
    { q: "とかげ座", a: "とかげ", img: "Lacerta_IAU.svg" },
    { q: "とけい座", a: "とけい", img: "Horologium_IAU.svg" },
    { q: "とびうお座", a: "とびうお", img: "Volans_IAU.svg" },
    { q: "とも座", a: "とも", img: "Puppis_IAU.svg" },
    { q: "はえ座", a: "はえ", img: "Musca_IAU.svg" },
    { q: "はくちょう座", a: "はくちょう", img: "Cygnus_IAU.svg" },
    { q: "はちぶんぎ座", a: "はちぶんぎ", img: "Octans_IAU.svg" },
    { q: "はと座", a: "はと", img: "Columba_IAU.svg" },
    { q: "ふうちょう座", a: "ふうちょう", img: "Apus_IAU.svg" },
    { q: "ふたご座", a: "ふたご", img: "Gemini_IAU.svg" },
    { q: "ペガスス座", a: "ペガスス", img: "Pegasus_IAU.svg" },
    { q: "へび座", a: "へび", img: "Serpens_IAU.svg" },
    { q: "へびつかい座", a: "へびつかい", img: "Ophiuchus_IAU.svg" },
    { q: "ヘルクレス座", a: "ヘルクレス", img: "Hercules_IAU.svg" },
    { q: "ペルセウス座", a: "ペルセウス", img: "Perseus_IAU.svg" },
    { q: "ぼうえんきょう座", a: "ぼうえんきょう", img: "Telescopium_IAU.svg" },
    { q: "ほうおう座", a: "ほうおう", img: "Phoenix_IAU.svg" },
    { q: "ほ座", a: "ほ", img: "Vela_IAU.svg" },
    { q: "ポンプ座", a: "ポンプ", img: "Antlia_IAU.svg" },
    { q: "みずがめ座", a: "みずがめ", img: "Aquarius_IAU.svg" },
    { q: "みずへび座", a: "みずへび", img: "Hydrus_IAU.svg" },
    { q: "みなみじゅうじ座", a: "みなみじゅうじ", img: "Crux_IAU.svg" },
    { q: "みなみのうお座", a: "みなみのうお", img: "Piscis_Austrinus_IAU.svg" },
    { q: "みなみのかんむり座", a: "みなみのかんむり", img: "Corona_Australis_IAU.svg" },
    { q: "みなみのさんかく座", a: "みなみのさんかく", img: "Triangulum_Australe_IAU.svg" },
    { q: "や座", a: "や", img: "Sagitta_IAU.svg" },
    { q: "やぎ座", a: "やぎ", img: "Capricornus_IAU.svg" },
    { q: "やまねこ座", a: "やまねこ", img: "Lynx_IAU.svg" },
    { q: "らしんばん座", a: "らしんばん", img: "Pyxis_IAU.svg" },
    { q: "りゅう座", a: "りゅう", img: "Draco_IAU.svg" },
    { q: "りゅうこつ座", a: "りゅうこつ", img: "Carina_IAU.svg" },
    { q: "りょうけん座", a: "りょうけん", img: "Canes_Venatici_IAU.svg" },
    { q: "レチクル座", a: "レチクル", img: "Reticulum_IAU.svg" },
    { q: "ろ座", a: "ろ", img: "Fornax_IAU.svg" },
    { q: "ろくぶんぎ座", a: "ろくぶんぎ", img: "Sextans_IAU.svg" },
    { q: "わし座", a: "わし", img: "Aquila_IAU.svg" }
];
// 3. 元素記号
const elementData = [
    { q: "1", a: "H (水素)", img: "" }, { q: "2", a: "He (ヘリウム)", img: "" }, { q: "3", a: "Li (リチウム)", img: "" }, { q: "4", a: "Be (ベリリウム)", img: "" }, { q: "5", a: "B (ホウ素)", img: "" }, { q: "6", a: "C (炭素)", img: "" }, { q: "7", a: "N (窒素)", img: "" }, { q: "8", a: "O (酸素)", img: "" }, { q: "9", a: "F (フッ素)", img: "" }, { q: "10", a: "Ne (ネオン)", img: "" },
    { q: "11", a: "Na (ナトリウム)", img: "" }, { q: "12", a: "Mg (マグネシウム)", img: "" }, { q: "13", a: "Al (アルミニウム)", img: "" }, { q: "14", a: "Si (ケイ素)", img: "" }, { q: "15", a: "P (リン)", img: "" }, { q: "16", a: "S (硫黄)", img: "" }, { q: "17", a: "Cl (塩素)", img: "" }, { q: "18", a: "Ar (アルゴン)", img: "" }, { q: "19", a: "K (カリウム)", img: "" }, { q: "20", a: "Ca (カルシウム)", img: "" },
    { q: "21", a: "Sc (スカンジウム)", img: "" }, { q: "22", a: "Ti (チタン)", img: "" }, { q: "23", a: "V (バナジウム)", img: "" }, { q: "24", a: "Cr (クロム)", img: "" }, { q: "25", a: "Mn (マンガン)", img: "" }, { q: "26", a: "Fe (鉄)", img: "" }, { q: "27", a: "Co (コバルト)", img: "" }, { q: "28", a: "Ni (ニッケル)", img: "" }, { q: "29", a: "Cu (銅)", img: "" }, { q: "30", a: "Zn (亜鉛)", img: "" },
    { q: "31", a: "Ga (ガリウム)", img: "" }, { q: "32", a: "Ge (ゲルマニウム)", img: "" }, { q: "33", a: "As (ヒ素)", img: "" }, { q: "34", a: "Se (セレン)", img: "" }, { q: "35", a: "Br (臭素)", img: "" }, { q: "36", a: "Kr (クリプトン)", img: "" }, { q: "37", a: "Rb (ルビジウム)", img: "" }, { q: "38", a: "Sr (ストロンチウム)", img: "" }, { q: "39", a: "Y (イットリウム)", img: "" }, { q: "40", a: "Zr (ジルコニウム)", img: "" },
    { q: "41", a: "Nb (ニオブ)", img: "" }, { q: "42", a: "Mo (モリブデン)", img: "" }, { q: "43", a: "Tc (テクネチウム)", img: "" }, { q: "44", a: "Ru (ルテニウム)", img: "" }, { q: "45", a: "Rh (ロジウム)", img: "" }, { q: "46", a: "Pd (パラジウム)", img: "" }, { q: "47", a: "Ag (銀)", img: "" }, { q: "48", a: "Cd (カドミウム)", img: "" }, { q: "49", a: "In (インジウム)", img: "" }, { q: "50", a: "Sn (スズ)", img: "" },
    { q: "51", a: "Sb (アンチモン)", img: "" }, { q: "52", a: "Te (テルル)", img: "" }, { q: "53", a: "I (ヨウ素)", img: "" }, { q: "54", a: "Xe (キセノン)", img: "" }, { q: "55", a: "Cs (セシウム)", img: "" }, { q: "56", a: "Ba (バリウム)", img: "" }, { q: "57", a: "La (ランタン)", img: "" }, { q: "58", a: "Ce (セリウム)", img: "" }, { q: "59", a: "Pr (プラセオジム)", img: "" }, { q: "60", a: "Nd (ネオジム)", img: "" },
    { q: "61", a: "Pm (プロメチウム)", img: "" }, { q: "62", a: "Sm (サマリウム)", img: "" }, { q: "63", a: "Eu (ユウロピウム)", img: "" }, { q: "64", a: "Gd (ガドリニウム)", img: "" }, { q: "65", a: "Tb (テルビウム)", img: "" }, { q: "66", a: "Dy (ジスプロシウム)", img: "" }, { q: "67", a: "Ho (ホルミウム)", img: "" }, { q: "68", a: "Er (エルビウム)", img: "" }, { q: "69", a: "Tm (ツリウム)", img: "" }, { q: "70", a: "Yb (イッテルビウム)", img: "" },
    { q: "71", a: "Lu (ルテチウム)", img: "" }, { q: "72", a: "Hf (ハフニウム)", img: "" }, { q: "73", a: "Ta (タンタル)", img: "" }, { q: "74", a: "W (タングステン)", img: "" }, { q: "75", a: "Re (レニウム)", img: "" }, { q: "76", a: "Os (オスミウム)", img: "" }, { q: "77", a: "Ir (イリジウム)", img: "" }, { q: "78", a: "Pt (白金)", img: "" }, { q: "79", a: "Au (金)", img: "" }, { q: "80", a: "Hg (水銀)", img: "" },
    { q: "81", a: "Tl (タリウム)", img: "" }, { q: "82", a: "Pb (鉛)", img: "" }, { q: "83", a: "Bi (ビスマス)", img: "" }, { q: "84", a: "Po (ポロニウム)", img: "" }, { q: "85", a: "At (アスタチン)", img: "" }, { q: "86", a: "Rn (ラドン)", img: "" }, { q: "87", a: "Fr (フランシウム)", img: "" }, { q: "88", a: "Ra (ラジウム)", img: "" }, { q: "89", a: "Ac (アクチニウム)", img: "" }, { q: "90", a: "Th (トリウム)", img: "" },
    { q: "91", a: "Pa (プロトアクチニウム)", img: "" }, { q: "92", a: "U (ウラン)", img: "" }, { q: "93", a: "Np (ネプツニウム)", img: "" }, { q: "94", a: "Pu (プルトニウム)", img: "" }, { q: "95", a: "Am (アメリシウム)", img: "" }, { q: "96", a: "Cm (キュリウム)", img: "" }, { q: "97", a: "Bk (バークリウム)", img: "" }, { q: "98", a: "Cf (カリホルニウム)", img: "" }, { q: "99", a: "Es (アインシュタイニウム)", img: "" }, { q: "100", a: "Fm (フェルミウム)", img: "" },
    { q: "101", a: "Md (メンデレビウム)", img: "" }, { q: "102", a: "No (ノーベリウム)", img: "" }, { q: "103", a: "Lr (ローレンシウム)", img: "" }, { q: "104", a: "Rf (ラザホージウム)", img: "" }, { q: "105", a: "Db (ドブニウム)", img: "" }, { q: "106", a: "Sg (シーボーギウム)", img: "" }, { q: "107", a: "Bh (ボーリウム)", img: "" }, { q: "108", a: "Hs (ハッシウム)", img: "" }, { q: "109", a: "Mt (マイトネリウム)", img: "" }, { q: "110", a: "Ds (ダームスタチウム)", img: "" },
    { q: "111", a: "Rg (レントゲニウム)", img: "" }, { q: "112", a: "Cn (コペルニシウム)", img: "" }, { q: "113", a: "Nh (ニホニウム)", img: "" }, { q: "114", a: "Fl (フレロビウム)", img: "" }, { q: "115", a: "Mc (モスコビウム)", img: "" }, { q: "116", a: "Lv (リバモリウム)", img: "" }, { q: "117", a: "Ts (テネシン)", img: "" }, { q: "118", a: "Og (オガネソン)", img: "" }
];

// 4. 8000m峰
const mountainData = [
    { q: "8,848m", a: "エベレスト", img: "" }, { q: "8,611m", a: "K2", img: "" }, { q: "8,586m", a: "カンチェンジュンガ", img: "" }, { q: "8,516m", a: "ローツェ", img: "" }, { q: "8,485m", a: "マカルー", img: "" }, { q: "8,188m", a: "チョ・オユー", img: "" }, { q: "8,167m", a: "ダウラギリ", img: "" }, { q: "8,163m", a: "マナスル", img: "" }, { q: "8,125m", a: "ナンガ・パルバット", img: "" }, { q: "8,091m", a: "アンナプルナ", img: "" }, { q: "8,080m", a: "ガッシャーブルムI峰", img: "" }, { q: "8,051m", a: "ブロード・ピーク", img: "" }, { q: "8,035m", a: "ガッシャーブルムII峰", img: "" }, { q: "8,027m", a: "シシャパンマ", img: "" }
];

// 5. モールス信号
const morseData = [
    { q: "・－", a: "A", img: "" }, { q: "－・・・", a: "B", img: "" }, { q: "－・－・", a: "C", img: "" }, { q: "－・・", a: "D", img: "" }, { q: "・", a: "E", img: "" }, { q: "・・－・", a: "F", img: "" }, { q: "－－・", a: "G", img: "" }, { q: "・・・・", a: "H", img: "" }, { q: "・・", a: "I", img: "" }, { q: "・－－－", a: "J", img: "" }, { q: "－・－", a: "K", img: "" }, { q: "・－・・", a: "L", img: "" }, { q: "－－", a: "M", img: "" }, { q: "－・", a: "N", img: "" }, { q: "－－－", a: "O", img: "" }, { q: "・－－・", a: "P", img: "" }, { q: "－－・－", a: "Q", img: "" }, { q: "・－・", a: "R", img: "" }, { q: "・・・", a: "S", img: "" }, { q: "－", a: "T", img: "" }, { q: "・・－", a: "U", img: "" }, { q: "・・・－", a: "V", img: "" }, { q: "・－－", a: "W", img: "" }, { q: "－・・－", a: "X", img: "" }, { q: "－・－－", a: "Y", img: "" }, { q: "－－・・", a: "Z", img: "" },
    { q: "・－－－－", a: "1", img: "" }, { q: "・・－－－", a: "2", img: "" }, { q: "・・・－－", a: "3", img: "" }, { q: "・・・・－", a: "4", img: "" }, { q: "・・・・・", a: "5", img: "" }, { q: "－・・・・", a: "6", img: "" }, { q: "－－・・・", a: "7", img: "" }, { q: "－－－・・", a: "8", img: "" }, { q: "－－－－・", a: "9", img: "" }, { q: "－－－－－", a: "0", img: "" }
];
// 6. アメリカ歴代大統領
const usPresidentData = [
    { q: "第1代", a: "ジョージ・ワシントン", img: "https://commons.wikimedia.org/wiki/Special:FilePath/Gilbert_Stuart_Williamstown_Portrait_of_George_Washington.jpg?width=320" },
    { q: "第2代", a: "ジョン・アダムズ", img: "https://commons.wikimedia.org/wiki/Special:FilePath/Official_Presidential_portrait_of_John_Adams_(by_John_Trumbull,_circa_1792).jpg?width=320" },
    { q: "第3代", a: "トーマス・ジェファーソン", img: "https://commons.wikimedia.org/wiki/Special:FilePath/Thomas_Jefferson_by_Rembrandt_Peale,_1800.jpg?width=320" },
    { q: "第4代", a: "ジェームズ・マディソン", img: "https://commons.wikimedia.org/wiki/Special:FilePath/James_Madison.jpg?width=320" },
    { q: "第5代", a: "ジェームズ・モンロー", img: "https://commons.wikimedia.org/wiki/Special:FilePath/James_Monroe_White_House_portrait_1819.jpg?width=320" },
    { q: "第6代", a: "ジョン・クィンシー・アダムズ", img: "https://commons.wikimedia.org/wiki/Special:FilePath/John_Quincy_Adams_by_GPA_Healy,_1858.jpg?width=320" },
    { q: "第7代", a: "アンドリュー・ジャクソン", img: "https://commons.wikimedia.org/wiki/Special:FilePath/Andrew_jackson_head.jpg?width=320" },
    { q: "第8代", a: "マーティン・ヴァン・ビューレン", img: "https://commons.wikimedia.org/wiki/Special:FilePath/Martin_Van_Buren_by_Mathew_Brady_c1855-58.jpg?width=320" },
    { q: "第9代", a: "ウィリアム・ハリソン", img: "https://commons.wikimedia.org/wiki/Special:FilePath/William_Henry_Harrison_by_James_Reid_Lambdin,_1835.jpg?width=320" },
    { q: "第10代", a: "ジョン・タイラー", img: "https://commons.wikimedia.org/wiki/Special:FilePath/John_Tyler.jpg?width=320" },
    { q: "第11代", a: "ジェームズ・K・ポーク", img: "https://commons.wikimedia.org/wiki/Special:FilePath/James_Knox_Polk_by_GPA_Healy.jpg?width=320" },
    { q: "第12代", a: "ザカリー・テイラー", img: "https://commons.wikimedia.org/wiki/Special:FilePath/Zachary_Taylor_restored_and_cropped.jpg?width=320" },
    { q: "第13代", a: "ミラード・フィルモア", img: "https://commons.wikimedia.org/wiki/Special:FilePath/Millard_Fillmore.jpg?width=320" },
    { q: "第14代", a: "フランクリン・ピアース", img: "https://commons.wikimedia.org/wiki/Special:FilePath/Franklin_Pierce.jpg?width=320" },
    { q: "第15代", a: "ジェームズ・ブキャナン", img: "https://commons.wikimedia.org/wiki/Special:FilePath/James_Buchanan.jpg?width=320" },
    { q: "第16代", a: "エイブラハム・リンカーン", img: "https://commons.wikimedia.org/wiki/Special:FilePath/Abraham_Lincoln_O-77_matte_collodion_print.jpg?width=320" },
    { q: "第17代", a: "アンドリュー・ジョンソン", img: "https://commons.wikimedia.org/wiki/Special:FilePath/President_Andrew_Johnson.jpg?width=320" },
    { q: "第18代", a: "ユリシーズ・S・グラント", img: "https://commons.wikimedia.org/wiki/Special:FilePath/Ulysses_S._Grant_1870-1880.jpg?width=320" },
    { q: "第19代", a: "ラザフォード・B・ヘイズ", img: "https://commons.wikimedia.org/wiki/Special:FilePath/President_Rutherford_Hayes_1870_-_1880_Restored.jpg?width=320" },
    { q: "第20代", a: "ジェームズ・A・ガーフィールド", img: "https://commons.wikimedia.org/wiki/Special:FilePath/James_Abram_Garfield,_photo_portrait_seated.jpg?width=320" },
    { q: "第21代", a: "チェスター・A・アーサー", img: "https://commons.wikimedia.org/wiki/Special:FilePath/Chester_Alan_Arthur.jpg?width=320" },
    { q: "第22代", a: "グロバー・クリーブランド", img: "https://commons.wikimedia.org/wiki/Special:FilePath/Grover_Cleveland_-_NARA_-_518139_(cropped).jpg?width=320" },
    { q: "第23代", a: "ベンジャミン・ハリソン", img: "https://commons.wikimedia.org/wiki/Special:FilePath/Benjamin_Harrison_by_Charles_Parker.jpg?width=320" },
    { q: "第24代", a: "グロバー・クリーブランド", img: "https://commons.wikimedia.org/wiki/Special:FilePath/Grover_Cleveland_-_NARA_-_518139_(cropped).jpg?width=320" },
    { q: "第25代", a: "ウィリアム・マッキンリー", img: "https://commons.wikimedia.org/wiki/Special:FilePath/President_William_McKinley.jpg?width=320" },
    { q: "第26代", a: "セオドア・ルーズベルト", img: "https://commons.wikimedia.org/wiki/Special:FilePath/President_Roosevelt_-_Pach_Bros.jpg?width=320" },
    { q: "第27代", a: "ウィリアム・ハワード・タフト", img: "https://commons.wikimedia.org/wiki/Special:FilePath/William_Howard_Taft_c1909.jpg?width=320" },
    { q: "第28代", a: "ウッドロウ・ウィルソン", img: "https://commons.wikimedia.org/wiki/Special:FilePath/Thomas_Woodrow_Wilson,_Harris_%26_Ewing_bw_photo_portrait,_1919_(cropped).jpg?width=320" },
    { q: "第29代", a: "ウォレン・G・ハーディング", img: "https://commons.wikimedia.org/wiki/Special:FilePath/Warren_G_Harding-Harris_%26_Ewing.jpg?width=320" },
    { q: "第30代", a: "カルビン・クーリッジ", img: "https://commons.wikimedia.org/wiki/Special:FilePath/Calvin_Coolidge_c1924.jpg?width=320" },
    { q: "第31代", a: "ハーバート・フーヴァー", img: "https://commons.wikimedia.org/wiki/Special:FilePath/President_Hoover_portrait.jpg?width=320" },
    { q: "第32代", a: "フランクリン・D・ルーズベルト", img: "https://commons.wikimedia.org/wiki/Special:FilePath/FDR_in_1933.jpg?width=320" },
    { q: "第33代", a: "ハリー・S・トルーマン", img: "https://commons.wikimedia.org/wiki/Special:FilePath/Harry_S._Truman.jpg?width=320" },
    { q: "第34代", a: "ドワイト・D・アイゼンハワー", img: "https://commons.wikimedia.org/wiki/Special:FilePath/Dwight_D._Eisenhower,_official_photo_portrait,_May_29,_1959.jpg?width=320" },
    { q: "第35代", a: "ジョン・F・ケネディ", img: "https://commons.wikimedia.org/wiki/Special:FilePath/John_F._Kennedy,_White_House_color_photo_portrait.jpg?width=320" },
    { q: "第36代", a: "リンドン・B・ジョンソン", img: "https://commons.wikimedia.org/wiki/Special:FilePath/37_Lyndon_Johnson_3x4.jpg?width=320" },
    { q: "第37代", a: "リチャード・ニクソン", img: "https://commons.wikimedia.org/wiki/Special:FilePath/Richard_M._Nixon,_ca._1935_-_1982_-_NARA_-_530679.jpg?width=320" },
    { q: "第38代", a: "ジェラルド・フォード", img: "https://commons.wikimedia.org/wiki/Special:FilePath/Gerald_Ford_presidential_portrait.jpg?width=320" },
    { q: "第39代", a: "ジミー・カーター", img: "https://commons.wikimedia.org/wiki/Special:FilePath/Jimmy_Carter_library_portrait_2.jpg?width=320" },
    { q: "第40代", a: "ロナルド・レーガン", img: "https://commons.wikimedia.org/wiki/Special:FilePath/Official_Portrait_of_President_Reagan_1981.jpg?width=320" },
    { q: "第41代", a: "ジョージ・H・W・ブッシュ", img: "https://commons.wikimedia.org/wiki/Special:FilePath/George_H._W._Bush_presidential_portrait.jpg?width=320" },
    { q: "第42代", a: "ビル・クリントン", img: "https://commons.wikimedia.org/wiki/Special:FilePath/President_Bill_Clinton.jpg?width=320" },
    { q: "第43代", a: "ジョージ・W・ブッシュ", img: "https://commons.wikimedia.org/wiki/Special:FilePath/George-W-Bush.jpeg?width=320" },
    { q: "第44代", a: "バラク・オバマ", img: "https://commons.wikimedia.org/wiki/Special:FilePath/President_Barack_Obama.jpg?width=320" },
    { q: "第45代", a: "ドナルド・トランプ", img: "https://commons.wikimedia.org/wiki/Special:FilePath/Donald_Trump_official_portrait.jpg?width=320" },
    { q: "第46代", a: "ジョー・バイデン", img: "https://commons.wikimedia.org/wiki/Special:FilePath/Joe_Biden_presidential_portrait.jpg?width=320" },
    { q: "第47代", a: "ドナルド・トランプ", img: "https://commons.wikimedia.org/wiki/Special:FilePath/Donald_Trump_official_portrait.jpg?width=320" }
];
// 7. 夏季オリンピック開催地
const olympicData = [
    { q: "1896年 第1回", a: "アテネ (ギリシャ)", img: "" }, { q: "1900年 第2回", a: "パリ (フランス)", img: "" }, { q: "1904年 第3回", a: "セントルイス (アメリカ)", img: "" }, { q: "1908年 第4回", a: "ロンドン (イギリス)", img: "" }, { q: "1912年 第5回", a: "ストックホルム (スウェーデン)", img: "" }, { q: "1916年 (第6回)", a: "ベルリン (中止)", img: "" }, { q: "1920年 第7回", a: "アントワープ (ベルギー)", img: "" }, { q: "1924年 第8回", a: "パリ (フランス)", img: "" }, { q: "1928年 第9回", a: "アムステルダム (オランダ)", img: "" }, { q: "1932年 第10回", a: "ロサンゼルス (アメリカ)", img: "" },
    { q: "1936年 第11回", a: "ベルリン (ドイツ)", img: "" }, { q: "1940年 (第12回)", a: "東京/ヘルシンキ (中止)", img: "" }, { q: "1944年 (第13回)", a: "ロンドン (中止)", img: "" }, { q: "1948年 第14回", a: "ロンドン (イギリス)", img: "" }, { q: "1952年 第15回", a: "ヘルシンキ (フィンランド)", img: "" }, { q: "1956年 第16回", a: "メルボルン (オーストラリア)", img: "" }, { q: "1960年 第17回", a: "ローマ (イタリア)", img: "" }, { q: "1964年 第18回", a: "東京 (日本)", img: "" }, { q: "1968年 第19回", a: "メキシコシティ (メキシコ)", img: "" }, { q: "1972年 第20回", a: "ミュンヘン (西ドイツ)", img: "" },
    { q: "1976年 第21回", a: "モントリオール (カナダ)", img: "" }, { q: "1980年 第22回", a: "モスクワ (ソ連)", img: "" }, { q: "1984年 第23回", a: "ロサンゼルス (アメリカ)", img: "" }, { q: "1988年 第24回", a: "ソウル (韓国)", img: "" }, { q: "1992年 第25回", a: "バルセロナ (スペイン)", img: "" }, { q: "1996年 第26回", a: "アトランタ (アメリカ)", img: "" }, { q: "2000年 第27回", a: "シドニー (オーストラリア)", img: "" }, { q: "2004年 第28回", a: "アテネ (ギリシャ)", img: "" }, { q: "2008年 第29回", a: "北京 (中国)", img: "" }, { q: "2012年 第30回", a: "ロンドン (イギリス)", img: "" },
    { q: "2016年 第31回", a: "リオデジャネイロ (ブラジル)", img: "" }, { q: "2021年 第32回", a: "東京 (日本)", img: "" }, { q: "2024年 第33回", a: "パリ (フランス)", img: "" }, { q: "2028年 第34回", a: "ロサンゼルス (アメリカ)", img: "" }, { q: "2032年 第35回", a: "ブリスベン (オーストラリア)", img: "" }
];

// 8. 山手線駅名
const yamanoteData = [
    { q: "JY01", a: "東京", img: "" }, { q: "JY02", a: "神田", img: "" }, { q: "JY03", a: "秋葉原", img: "" }, { q: "JY04", a: "御徒町", img: "" }, { q: "JY05", a: "上野", img: "" }, { q: "JY06", a: "鶯谷", img: "" }, { q: "JY07", a: "日暮里", img: "" }, { q: "JY08", a: "西日暮里", img: "" }, { q: "JY09", a: "田端", img: "" }, { q: "JY10", a: "駒込", img: "" },
    { q: "JY11", a: "巣鴨", img: "" }, { q: "JY12", a: "大塚", img: "" }, { q: "JY13", a: "池袋", img: "" }, { q: "JY14", a: "目白", img: "" }, { q: "JY15", a: "高田馬場", img: "" }, { q: "JY16", a: "新大久保", img: "" }, { q: "JY17", a: "新宿", img: "" }, { q: "JY18", a: "代々木", img: "" }, { q: "JY19", a: "原宿", img: "" }, { q: "JY20", a: "渋谷", img: "" },
    { q: "JY21", a: "恵比寿", img: "" }, { q: "JY22", a: "目黒", img: "" }, { q: "JY23", a: "五反田", img: "" }, { q: "JY24", a: "大崎", img: "" }, { q: "JY25", a: "品川", img: "" }, { q: "JY26", a: "高輪ゲートウェイ", img: "" }, { q: "JY27", a: "田町", img: "" }, { q: "JY28", a: "浜松町", img: "" }, { q: "JY29", a: "新橋", img: "" }, { q: "JY30", a: "有楽町", img: "" }
];

// 🌟 197カ国完全版！世界の国旗データ（6大陸タグ付き）
const worldFlagData = [
    // 【アジア】
    { q: "日本", a: "日本", img: "Flag_of_Japan.svg", region: "asia" },
    { q: "韓国", a: "大韓民国", img: "Flag_of_South_Korea.svg", region: "asia" },
    { q: "北朝鮮", a: "朝鮮民主主義人民共和国", img: "Flag_of_North_Korea.svg", region: "asia" },
    { q: "中国", a: "中華人民共和国", img: "Flag_of_the_People's_Republic_of_China.svg", region: "asia" },
    { q: "モンゴル", a: "モンゴル", img: "Flag_of_Mongolia.svg", region: "asia" },
    { q: "台湾", a: "台湾", img: "Flag_of_the_Republic_of_China.svg", region: "asia" },
    { q: "フィリピン", a: "フィリピン", img: "Flag_of_the_Philippines.svg", region: "asia" },
    { q: "ベトナム", a: "ベトナム", img: "Flag_of_Vietnam.svg", region: "asia" },
    { q: "ラオス", a: "ラオス", img: "Flag_of_Laos.svg", region: "asia" },
    { q: "カンボジア", a: "カンボジア", img: "Flag_of_Cambodia.svg", region: "asia" },
    { q: "タイ", a: "タイ王国", img: "Flag_of_Thailand.svg", region: "asia" },
    { q: "ミャンマー", a: "ミャンマー", img: "Flag_of_Myanmar.svg", region: "asia" },
    { q: "マレーシア", a: "マレーシア", img: "Flag_of_Malaysia.svg", region: "asia" },
    { q: "シンガポール", a: "シンガポール", img: "Flag_of_Singapore.svg", region: "asia" },
    { q: "インドネシア", a: "インドネシア", img: "Flag_of_Indonesia.svg", region: "asia" },
    { q: "ブルネイ", a: "ブルネイ", img: "Flag_of_Brunei.svg", region: "asia" },
    { q: "東ティモール", a: "東ティモール", img: "Flag_of_East_Timor.svg", region: "asia" },
    { q: "インド", a: "インド", img: "Flag_of_India.svg", region: "asia" },
    { q: "ネパール", a: "ネパール", img: "Flag_of_Nepal.svg", region: "asia" },
    { q: "ブータン", a: "ブータン", img: "Flag_of_Bhutan.svg", region: "asia" },
    { q: "バングラデシュ", a: "バングラデシュ", img: "Flag_of_Bangladesh.svg", region: "asia" },
    { q: "スリランカ", a: "スリランカ", img: "Flag_of_Sri_Lanka.svg", region: "asia" },
    { q: "モルディブ", a: "モルディブ", img: "Flag_of_Maldives.svg", region: "asia" },
    { q: "パキスタン", a: "パキスタン", img: "Flag_of_Pakistan.svg", region: "asia" },
    { q: "アフガニスタン", a: "アフガニスタン", img: "Flag_of_Afghanistan.svg", region: "asia" },
    { q: "イラン", a: "イラン", img: "Flag_of_Iran.svg", region: "asia" },
    { q: "イラク", a: "イラク", img: "Flag_of_Iraq.svg", region: "asia" },
    { q: "シリア", a: "シリア", img: "Flag_of_Syria.svg", region: "asia" },
    { q: "レバノン", a: "レバノン", img: "Flag_of_Lebanon.svg", region: "asia" },
    { q: "イスラエル", a: "イスラエル", img: "Flag_of_Israel.svg", region: "asia" },
    { q: "ヨルダン", a: "ヨルダン", img: "Flag_of_Jordan.svg", region: "asia" },
    { q: "サウジアラビア", a: "サウジアラビア", img: "Flag_of_Saudi_Arabia.svg", region: "asia" },
    { q: "クウェート", a: "クウェート", img: "Flag_of_Kuwait.svg", region: "asia" },
    { q: "バーレーン", a: "バーレーン", img: "Flag_of_Bahrain.svg", region: "asia" },
    { q: "カタール", a: "カタール", img: "Flag_of_Qatar.svg", region: "asia" },
    { q: "アラブ首長国連邦", a: "UAE（アラブ首長国連邦）", img: "Flag_of_the_United_Arab_Emirates.svg", region: "asia" },
    { q: "オマーン", a: "オマーン", img: "Flag_of_Oman.svg", region: "asia" },
    { q: "イエメン", a: "イエメン", img: "Flag_of_Yemen.svg", region: "asia" },
    { q: "トルコ", a: "トルコ", img: "Flag_of_Turkey.svg", region: "asia" },
    { q: "キプロス", a: "キプロス", img: "Flag_of_Cyprus.svg", region: "asia" },
    { q: "ジョージア", a: "ジョージア", img: "Flag_of_Georgia.svg", region: "asia" },
    { q: "アルメニア", a: "アルメニア", img: "Flag_of_Armenia.svg", region: "asia" },
    { q: "アゼルバイジャン", a: "アゼルバイジャン", img: "Flag_of_Azerbaijan.svg", region: "asia" },
    { q: "カザフスタン", a: "カザフスタン", img: "Flag_of_Kazakhstan.svg", region: "asia" },
    { q: "ウズベキスタン", a: "ウズベキスタン", img: "Flag_of_Uzbekistan.svg", region: "asia" },
    { q: "トルクメニスタン", a: "トルクメニスタン", img: "Flag_of_Turkmenistan.svg", region: "asia" },
    { q: "タジキスタン", a: "タジキスタン", img: "Flag_of_Tajikistan.svg", region: "asia" },
    { q: "キルギス", a: "キルギス", img: "Flag_of_Kyrgyzstan.svg", region: "asia" },

    // 【ヨーロッパ】
    { q: "イギリス", a: "イギリス", img: "Flag_of_the_United_Kingdom.svg", region: "europe" },
    { q: "アイルランド", a: "アイルランド", img: "Flag_of_Ireland.svg", region: "europe" },
    { q: "フランス", a: "フランス", img: "Flag_of_France.svg", region: "europe" },
    { q: "ドイツ", a: "ドイツ", img: "Flag_of_Germany.svg", region: "europe" },
    { q: "イタリア", a: "イタリア", img: "Flag_of_Italy.svg", region: "europe" },
    { q: "スペイン", a: "スペイン", img: "Flag_of_Spain.svg", region: "europe" },
    { q: "ポルトガル", a: "ポルトガル", img: "Flag_of_Portugal.svg", region: "europe" },
    { q: "アンドラ", a: "アンドラ", img: "Flag_of_Andorra.svg", region: "europe" },
    { q: "モナコ", a: "モナコ", img: "Flag_of_Monaco.svg", region: "europe" },
    { q: "バチカン", a: "バチカン市国", img: "Flag_of_the_Vatican_City.svg", region: "europe" },
    { q: "サンマリノ", a: "サンマリノ", img: "Flag_of_San_Marino.svg", region: "europe" },
    { q: "マルタ", a: "マルタ", img: "Flag_of_Malta.svg", region: "europe" },
    { q: "ギリシャ", a: "ギリシャ", img: "Flag_of_Greece.svg", region: "europe" },
    { q: "アルバニア", a: "アルバニア", img: "Flag_of_Albania.svg", region: "europe" },
    { q: "北マケドニア", a: "北マケドニア", img: "Flag_of_North_Macedonia.svg", region: "europe" },
    { q: "ブルガリア", a: "ブルガリア", img: "Flag_of_Bulgaria.svg", region: "europe" },
    { q: "ルーマニア", a: "ルーマニア", img: "Flag_of_Romania.svg", region: "europe" },
    { q: "セルビア", a: "セルビア", img: "Flag_of_Serbia.svg", region: "europe" },
    { q: "モンテネグロ", a: "モンテネグロ", img: "Flag_of_Montenegro.svg", region: "europe" },
    { q: "ボスニア・ヘルツェゴビナ", a: "ボスニア・ヘルツェゴビナ", img: "Flag_of_Bosnia_and_Herzegovina.svg", region: "europe" },
    { q: "クロアチア", a: "クロアチア", img: "Flag_of_Croatia.svg", region: "europe" },
    { q: "スロベニア", a: "スロベニア", img: "Flag_of_Slovenia.svg", region: "europe" },
    { q: "ハンガリー", a: "ハンガリー", img: "Flag_of_Hungary.svg", region: "europe" },
    { q: "オーストリア", a: "オーストリア", img: "Flag_of_Austria.svg", region: "europe" },
    { q: "スイス", a: "スイス", img: "Flag_of_Switzerland.svg", region: "europe" },
    { q: "リヒテンシュタイン", a: "リヒテンシュタイン", img: "Flag_of_Liechtenstein.svg", region: "europe" },
    { q: "チェコ", a: "チェコ", img: "Flag_of_the_Czech_Republic.svg", region: "europe" },
    { q: "スロバキア", a: "スロバキア", img: "Flag_of_Slovakia.svg", region: "europe" },
    { q: "ポーランド", a: "ポーランド", img: "Flag_of_Poland.svg", region: "europe" },
    { q: "オランダ", a: "オランダ", img: "Flag_of_the_Netherlands.svg", region: "europe" },
    { q: "ベルギー", a: "ベルギー", img: "Flag_of_Belgium.svg", region: "europe" },
    { q: "ルクセンブルク", a: "ルクセンブルク", img: "Flag_of_Luxembourg.svg", region: "europe" },
    { q: "ウクライナ", a: "ウクライナ", img: "Flag_of_Ukraine.svg", region: "europe" },
    { q: "ベラルーシ", a: "ベラルーシ", img: "Flag_of_Belarus.svg", region: "europe" },
    { q: "モルドバ", a: "モルドバ", img: "Flag_of_Moldova.svg", region: "europe" },
    { q: "ロシア", a: "ロシア", img: "Flag_of_Russia.svg", region: "europe" },
    { q: "エストニア", a: "エストニア", img: "Flag_of_Estonia.svg", region: "europe" },
    { q: "ラトビア", a: "ラトビア", img: "Flag_of_Latvia.svg", region: "europe" },
    { q: "リトアニア", a: "リトアニア", img: "Flag_of_Lithuania.svg", region: "europe" },
    { q: "フィンランド", a: "フィンランド", img: "Flag_of_Finland.svg", region: "europe" },
    { q: "スウェーデン", a: "スウェーデン", img: "Flag_of_Sweden.svg", region: "europe" },
    { q: "ノルウェー", a: "ノルウェー", img: "Flag_of_Norway.svg", region: "europe" },
    { q: "デンマーク", a: "デンマーク", img: "Flag_of_Denmark.svg", region: "europe" },
    { q: "アイスランド", a: "アイスランド", img: "Flag_of_Iceland.svg", region: "europe" },
    { q: "コソボ", a: "コソボ", img: "Flag_of_Kosovo.svg", region: "europe" },

    // 【アフリカ】
    { q: "エジプト", a: "エジプト", img: "Flag_of_Egypt.svg", region: "africa" },
    { q: "リビア", a: "リビア", img: "Flag_of_Libya.svg", region: "africa" },
    { q: "チュニジア", a: "チュニジア", img: "Flag_of_Tunisia.svg", region: "africa" },
    { q: "アルジェリア", a: "アルジェリア", img: "Flag_of_Algeria.svg", region: "africa" },
    { q: "モロッコ", a: "モロッコ", img: "Flag_of_Morocco.svg", region: "africa" },
    { q: "モーリタニア", a: "モーリタニア", img: "Flag_of_Mauritania.svg", region: "africa" },
    { q: "マリ", a: "マリ", img: "Flag_of_Mali.svg", region: "africa" },
    { q: "ニジェール", a: "ニジェール", img: "Flag_of_Niger.svg", region: "africa" },
    { q: "チャド", a: "チャド", img: "Flag_of_Chad.svg", region: "africa" },
    { q: "スーダン", a: "スーダン", img: "Flag_of_Sudan.svg", region: "africa" },
    { q: "南スーダン", a: "南スーダン", img: "Flag_of_South_Sudan.svg", region: "africa" },
    { q: "エリトリア", a: "エリトリア", img: "Flag_of_Eritrea.svg", region: "africa" },
    { q: "ジブチ", a: "ジブチ", img: "Flag_of_Djibouti.svg", region: "africa" },
    { q: "ソマリア", a: "ソマリア", img: "Flag_of_Somalia.svg", region: "africa" },
    { q: "エチオピア", a: "エチオピア", img: "Flag_of_Ethiopia.svg", region: "africa" },
    { q: "セネガル", a: "セネガル", img: "Flag_of_Senegal.svg", region: "africa" },
    { q: "ガンビア", a: "ガンビア", img: "Flag_of_the_Gambia.svg", region: "africa" },
    { q: "ギニアビサウ", a: "ギニアビサウ", img: "Flag_of_Guinea-Bissau.svg", region: "africa" },
    { q: "ギニア", a: "ギニア", img: "Flag_of_Guinea.svg", region: "africa" },
    { q: "シエラレオネ", a: "シエラレオネ", img: "Flag_of_Sierra_Leone.svg", region: "africa" },
    { q: "リベリア", a: "リベリア", img: "Flag_of_Liberia.svg", region: "africa" },
    { q: "コートジボワール", a: "コートジボワール", img: "Flag_of_Cote_d'Ivoire.svg", region: "africa" },
    { q: "ブルキナファソ", a: "ブルキナファソ", img: "Flag_of_Burkina_Faso.svg", region: "africa" },
    { q: "ガーナ", a: "ガーナ", img: "Flag_of_Ghana.svg", region: "africa" },
    { q: "トーゴ", a: "トーゴ", img: "Flag_of_Togo.svg", region: "africa" },
    { q: "ベナン", a: "ベナン", img: "Flag_of_Benin.svg", region: "africa" },
    { q: "ナイジェリア", a: "ナイジェリア", img: "Flag_of_Nigeria.svg", region: "africa" },
    { q: "カメルーン", a: "カメルーン", img: "Flag_of_Cameroon.svg", region: "africa" },
    { q: "中央アフリカ", a: "中央アフリカ", img: "Flag_of_the_Central_African_Republic.svg", region: "africa" },
    { q: "赤道ギニア", a: "赤道ギニア", img: "Flag_of_Equatorial_Guinea.svg", region: "africa" },
    { q: "ガボン", a: "ガボン", img: "Flag_of_Gabon.svg", region: "africa" },
    { q: "コンゴ共和国", a: "コンゴ共和国", img: "Flag_of_the_Republic_of_the_Congo.svg", region: "africa" },
    { q: "コンゴ民主共和国", a: "コンゴ民主共和国", img: "Flag_of_the_Democratic_Republic_of_the_Congo.svg", region: "africa" },
    { q: "サントメ・プリンシペ", a: "サントメ・プリンシペ", img: "Flag_of_Sao_Tome_and_Principe.svg", region: "africa" },
    { q: "ルワンダ", a: "ルワンダ", img: "Flag_of_Rwanda.svg", region: "africa" },
    { q: "ブルンジ", a: "ブルンジ", img: "Flag_of_Burundi.svg", region: "africa" },
    { q: "ウガンダ", a: "ウガンダ", img: "Flag_of_Uganda.svg", region: "africa" },
    { q: "ケニア", a: "ケニア", img: "Flag_of_Kenya.svg", region: "africa" },
    { q: "タンザニア", a: "タンザニア", img: "Flag_of_Tanzania.svg", region: "africa" },
    { q: "アンゴラ", a: "アンゴラ", img: "Flag_of_Angola.svg", region: "africa" },
    { q: "ザンビア", a: "ザンビア", img: "Flag_of_Zambia.svg", region: "africa" },
    { q: "マラウイ", a: "マラウイ", img: "Flag_of_Malawi.svg", region: "africa" },
    { q: "モザンビーク", a: "モザンビーク", img: "Flag_of_Mozambique.svg", region: "africa" },
    { q: "ジンバブエ", a: "ジンバブエ", img: "Flag_of_Zimbabwe.svg", region: "africa" },
    { q: "ボツワナ", a: "ボツワナ", img: "Flag_of_Botswana.svg", region: "africa" },
    { q: "ナミビア", a: "ナミビア", img: "Flag_of_Namibia.svg", region: "africa" },
    { q: "南アフリカ", a: "南アフリカ共和国", img: "Flag_of_South_Africa.svg", region: "africa" },
    { q: "レソト", a: "レソト", img: "Flag_of_Lesotho.svg", region: "africa" },
    { q: "エスワティニ", a: "エスワティニ", img: "Flag_of_Eswatini.svg", region: "africa" },
    { q: "マダガスカル", a: "マダガスカル", img: "Flag_of_Madagascar.svg", region: "africa" },
    { q: "モーリシャス", a: "モーリシャス", img: "Flag_of_Mauritius.svg", region: "africa" },
    { q: "セーシェル", a: "セーシェル", img: "Flag_of_Seychelles.svg", region: "africa" },
    { q: "コモロ", a: "コモロ", img: "Flag_of_the_Comoros.svg", region: "africa" },
    { q: "カーボベルデ", a: "カーボベルデ", img: "Flag_of_Cape_Verde.svg", region: "africa" },

    // 【北アメリカ】
    { q: "アメリカ", a: "アメリカ合衆国", img: "Flag_of_the_United_States.svg", region: "north_america" },
    { q: "カナダ", a: "カナダ", img: "Flag_of_Canada.svg", region: "north_america" },
    { q: "メキシコ", a: "メキシコ", img: "Flag_of_Mexico.svg", region: "north_america" },
    { q: "グアテマラ", a: "グアテマラ", img: "Flag_of_Guatemala.svg", region: "north_america" },
    { q: "ベリーズ", a: "ベリーズ", img: "Flag_of_Belize.svg", region: "north_america" },
    { q: "ホンジュラス", a: "ホンジュラス", img: "Flag_of_Honduras.svg", region: "north_america" },
    { q: "エルサルバドル", a: "エルサルバドル", img: "Flag_of_El_Salvador.svg", region: "north_america" },
    { q: "ニカラグア", a: "ニカラグア", img: "Flag_of_Nicaragua.svg", region: "north_america" },
    { q: "コスタリカ", a: "コスタリカ", img: "Flag_of_Costa_Rica.svg", region: "north_america" },
    { q: "パナマ", a: "パナマ", img: "Flag_of_Panama.svg", region: "north_america" },
    { q: "キューバ", a: "キューバ", img: "Flag_of_Cuba.svg", region: "north_america" },
    { q: "ジャマイカ", a: "ジャマイカ", img: "Flag_of_Jamaica.svg", region: "north_america" },
    { q: "ハイチ", a: "ハイチ", img: "Flag_of_Haiti.svg", region: "north_america" },
    { q: "ドミニカ共和国", a: "ドミニカ共和国", img: "Flag_of_the_Dominican_Republic.svg", region: "north_america" },
    { q: "バハマ", a: "バハマ", img: "Flag_of_the_Bahamas.svg", region: "north_america" },
    { q: "アンティグア・バーブーダ", a: "アンティグア・バーブーダ", img: "Flag_of_Antigua_and_Barbuda.svg", region: "north_america" },
    { q: "セントクリストファー・ネイビス", a: "セントクリストファー・ネイビス", img: "Flag_of_Saint_Kitts_and_Nevis.svg", region: "north_america" },
    { q: "ドミニカ国", a: "ドミニカ国", img: "Flag_of_Dominica.svg", region: "north_america" },
    { q: "セントルシア", a: "セントルシア", img: "Flag_of_Saint_Lucia.svg", region: "north_america" },
    { q: "セントビンセント・グレナディーン", a: "セントビンセント・グレナディーン", img: "Flag_of_Saint_Vincent_and_the_Grenadines.svg", region: "north_america" },
    { q: "バルバドス", a: "バルバドス", img: "Flag_of_Barbados.svg", region: "north_america" },
    { q: "グレナダ", a: "グレナダ", img: "Flag_of_Grenada.svg", region: "north_america" },
    { q: "トリニダード・トバゴ", a: "トリニダード・トバゴ", img: "Flag_of_Trinidad_and_Tobago.svg", region: "north_america" },

    // 【南アメリカ】
    { q: "コロンビア", a: "コロンビア", img: "Flag_of_Colombia.svg", region: "south_america" },
    { q: "ベネズエラ", a: "ベネズエラ", img: "Flag_of_Venezuela.svg", region: "south_america" },
    { q: "ガイアナ", a: "ガイアナ", img: "Flag_of_Guyana.svg", region: "south_america" },
    { q: "スリナム", a: "スリナム", img: "Flag_of_Suriname.svg", region: "south_america" },
    { q: "エクアドル", a: "エクアドル", img: "Flag_of_Ecuador.svg", region: "south_america" },
    { q: "ペルー", a: "ペルー", img: "Flag_of_Peru.svg", region: "south_america" },
    { q: "ブラジル", a: "ブラジル", img: "Flag_of_Brazil.svg", region: "south_america" },
    { q: "ボリビア", a: "ボリビア", img: "Flag_of_Bolivia.svg", region: "south_america" },
    { q: "パラグアイ", a: "パラグアイ", img: "Flag_of_Paraguay.svg", region: "south_america" },
    { q: "チリ", a: "チリ", img: "Flag_of_Chile.svg", region: "south_america" },
    { q: "アルゼンチン", a: "アルゼンチン", img: "Flag_of_Argentina.svg", region: "south_america" },
    { q: "ウルグアイ", a: "ウルグアイ", img: "Flag_of_Uruguay.svg", region: "south_america" },

    // 【オセアニア】
    { q: "オーストラリア", a: "オーストラリア", img: "Flag_of_Australia.svg", region: "oceania" },
    { q: "ニュージーランド", a: "ニュージーランド", img: "Flag_of_New_Zealand.svg", region: "oceania" },
    { q: "パプアニューギニア", a: "パプアニューギニア", img: "Flag_of_Papua_New_Guinea.svg", region: "oceania" },
    { q: "ソロモン諸島", a: "ソロモン諸島", img: "Flag_of_the_Solomon_Islands.svg", region: "oceania" },
    { q: "バヌアツ", a: "バヌアツ", img: "Flag_of_Vanuatu.svg", region: "oceania" },
    { q: "フィジー", a: "フィジー", img: "Flag_of_Fiji.svg", region: "oceania" },
    { q: "パラオ", a: "パラオ", img: "Flag_of_Palau.svg", region: "oceania" },
    { q: "ミクロネシア連邦", a: "ミクロネシア連邦", img: "Flag_of_Micronesia.svg", region: "oceania" },
    { q: "マーシャル諸島", a: "マーシャル諸島", img: "Flag_of_the_Marshall_Islands.svg", region: "oceania" },
    { q: "ナウル", a: "ナウル", img: "Flag_of_Nauru.svg", region: "oceania" },
    { q: "キリバス", a: "キリバス", img: "Flag_of_Kiribati.svg", region: "oceania" },
    { q: "ツバル", a: "ツバル", img: "Flag_of_Tuvalu.svg", region: "oceania" },
    { q: "サモア", a: "サモア", img: "Flag_of_Samoa.svg", region: "oceania" },
    { q: "トンガ", a: "トンガ", img: "Flag_of_Tonga.svg", region: "oceania" },
    { q: "クック諸島", a: "クック諸島", img: "Flag_of_the_Cook_Islands.svg", region: "oceania" },
    { q: "ニウエ", a: "ニウエ", img: "Flag_of_Niue.svg", region: "oceania" }
];
// 🌟 首都データ（197カ国完全版・6大陸タグ付き）
const capitalData = [
    // 【アジア】
    { q: "日本", a: "東京", region: "asia" },
    { q: "韓国", a: "ソウル", region: "asia" },
    { q: "北朝鮮", a: "平壌（ピョンヤン）", region: "asia" },
    { q: "中国", a: "北京（ペキン）", region: "asia" },
    { q: "モンゴル", a: "ウランバートル", region: "asia" },
    { q: "台湾", a: "台北（タイペイ）", region: "asia" },
    { q: "フィリピン", a: "マニラ", region: "asia" },
    { q: "ベトナム", a: "ハノイ", region: "asia" },
    { q: "ラオス", a: "ビエンチャン", region: "asia" },
    { q: "カンボジア", a: "プノンペン", region: "asia" },
    { q: "タイ", a: "バンコク", region: "asia" },
    { q: "ミャンマー", a: "ネピドー", region: "asia" },
    { q: "マレーシア", a: "クアラルンプール", region: "asia" },
    { q: "シンガポール", a: "シンガポール", region: "asia" },
    { q: "インドネシア", a: "ジャカルタ", region: "asia" },
    { q: "ブルネイ", a: "バンダルスリブガワン", region: "asia" },
    { q: "東ティモール", a: "ディリ", region: "asia" },
    { q: "インド", a: "ニューデリー", region: "asia" },
    { q: "ネパール", a: "カトマンズ", region: "asia" },
    { q: "ブータン", a: "ティンプー", region: "asia" },
    { q: "バングラデシュ", a: "ダッカ", region: "asia" },
    { q: "スリランカ", a: "スリジャヤワルダナプラコッテ", region: "asia" },
    { q: "モルディブ", a: "マレ", region: "asia" },
    { q: "パキスタン", a: "イスラマバード", region: "asia" },
    { q: "アフガニスタン", a: "カブール", region: "asia" },
    { q: "イラン", a: "テヘラン", region: "asia" },
    { q: "イラク", a: "バグダッド", region: "asia" },
    { q: "シリア", a: "ダマスカス", region: "asia" },
    { q: "レバノン", a: "ベイルート", region: "asia" },
    { q: "イスラエル", a: "エルサレム", region: "asia" },
    { q: "ヨルダン", a: "アンマン", region: "asia" },
    { q: "サウジアラビア", a: "リヤド", region: "asia" },
    { q: "クウェート", a: "クウェート", region: "asia" },
    { q: "バーレーン", a: "マナマ", region: "asia" },
    { q: "カタール", a: "ドーハ", region: "asia" },
    { q: "アラブ首長国連邦", a: "アブダビ", region: "asia" },
    { q: "オマーン", a: "マスカット", region: "asia" },
    { q: "イエメン", a: "サヌア", region: "asia" },
    { q: "トルコ", a: "アンカラ", region: "asia" },
    { q: "キプロス", a: "ニコシア", region: "asia" },
    { q: "ジョージア", a: "トビリシ", region: "asia" },
    { q: "アルメニア", a: "エレバン", region: "asia" },
    { q: "アゼルバイジャン", a: "バクー", region: "asia" },
    { q: "カザフスタン", a: "アスタナ", region: "asia" },
    { q: "ウズベキスタン", a: "タシュケント", region: "asia" },
    { q: "トルクメニスタン", a: "アシガバート", region: "asia" },
    { q: "タジキスタン", a: "ドゥシャンベ", region: "asia" },
    { q: "キルギス", a: "ビシュケク", region: "asia" },

    // 【ヨーロッパ】
    { q: "イギリス", a: "ロンドン", region: "europe" },
    { q: "アイルランド", a: "ダブリン", region: "europe" },
    { q: "フランス", a: "パリ", region: "europe" },
    { q: "ドイツ", a: "ベルリン", region: "europe" },
    { q: "イタリア", a: "ローマ", region: "europe" },
    { q: "スペイン", a: "マドリード", region: "europe" },
    { q: "ポルトガル", a: "リスボン", region: "europe" },
    { q: "アンドラ", a: "アンドララベリャ", region: "europe" },
    { q: "モナコ", a: "モナコ", region: "europe" },
    { q: "バチカン", a: "バチカン", region: "europe" },
    { q: "サンマリノ", a: "サンマリノ", region: "europe" },
    { q: "マルタ", a: "バレッタ", region: "europe" },
    { q: "ギリシャ", a: "アテネ", region: "europe" },
    { q: "アルバニア", a: "ティラナ", region: "europe" },
    { q: "北マケドニア", a: "スコピエ", region: "europe" },
    { q: "ブルガリア", a: "ソフィア", region: "europe" },
    { q: "ルーマニア", a: "ブカレスト", region: "europe" },
    { q: "セルビア", a: "ベオグラード", region: "europe" },
    { q: "モンテネグロ", a: "ポドゴリツァ", region: "europe" },
    { q: "ボスニア・ヘルツェゴビナ", a: "サラエボ", region: "europe" },
    { q: "クロアチア", a: "ザグレブ", region: "europe" },
    { q: "スロベニア", a: "リュブリャナ", region: "europe" },
    { q: "ハンガリー", a: "ブダペスト", region: "europe" },
    { q: "オーストリア", a: "ウィーン", region: "europe" },
    { q: "スイス", a: "ベルン", region: "europe" },
    { q: "リヒテンシュタイン", a: "ファドゥーツ", region: "europe" },
    { q: "チェコ", a: "プラハ", region: "europe" },
    { q: "スロバキア", a: "ブラチスラバ", region: "europe" },
    { q: "ポーランド", a: "ワルシャワ", region: "europe" },
    { q: "オランダ", a: "アムステルダム", region: "europe" },
    { q: "ベルギー", a: "ブリュッセル", region: "europe" },
    { q: "ルクセンブルク", a: "ルクセンブルク", region: "europe" },
    { q: "ウクライナ", a: "キーウ", region: "europe" },
    { q: "ベラルーシ", a: "ミンスク", region: "europe" },
    { q: "モルドバ", a: "キシナウ", region: "europe" },
    { q: "ロシア", a: "モスクワ", region: "europe" },
    { q: "エストニア", a: "タリン", region: "europe" },
    { q: "ラトビア", a: "リガ", region: "europe" },
    { q: "リトアニア", a: "ビリニュス", region: "europe" },
    { q: "フィンランド", a: "ヘルシンキ", region: "europe" },
    { q: "スウェーデン", a: "ストックホルム", region: "europe" },
    { q: "ノルウェー", a: "オスロ", region: "europe" },
    { q: "デンマーク", a: "コペンハーゲン", region: "europe" },
    { q: "アイスランド", a: "レイキャビク", region: "europe" },
    { q: "コソボ", a: "プリシュティナ", region: "europe" },

    // 【アフリカ】
    { q: "エジプト", a: "カイロ", region: "africa" },
    { q: "リビア", a: "トリポリ", region: "africa" },
    { q: "チュニジア", a: "チュニス", region: "africa" },
    { q: "アルジェリア", a: "アルジェ", region: "africa" },
    { q: "モロッコ", a: "ラバト", region: "africa" },
    { q: "モーリタニア", a: "ヌアクショット", region: "africa" },
    { q: "マリ", a: "バマコ", region: "africa" },
    { q: "ニジェール", a: "ニアメ", region: "africa" },
    { q: "チャド", a: "ンジャメナ", region: "africa" },
    { q: "スーダン", a: "ハルツーム", region: "africa" },
    { q: "南スーダン", a: "ジュバ", region: "africa" },
    { q: "エリトリア", a: "アスマラ", region: "africa" },
    { q: "ジブチ", a: "ジブチ", region: "africa" },
    { q: "ソマリア", a: "モガディシュ", region: "africa" },
    { q: "エチオピア", a: "アディスアベバ", region: "africa" },
    { q: "セネガル", a: "ダカール", region: "africa" },
    { q: "ガンビア", a: "バンジュール", region: "africa" },
    { q: "ギニアビサウ", a: "ビサウ", region: "africa" },
    { q: "ギニア", a: "コナクリ", region: "africa" },
    { q: "シエラレオネ", a: "フリータウン", region: "africa" },
    { q: "リベリア", a: "モンロビア", region: "africa" },
    { q: "コートジボワール", a: "ヤムスクロ", region: "africa" },
    { q: "ブルキナファソ", a: "ワガドゥグー", region: "africa" },
    { q: "ガーナ", a: "アクラ", region: "africa" },
    { q: "トーゴ", a: "ロメ", region: "africa" },
    { q: "ベナン", a: "ポルトノボ", region: "africa" },
    { q: "ナイジェリア", a: "アブジャ", region: "africa" },
    { q: "カメルーン", a: "ヤウンデ", region: "africa" },
    { q: "中央アフリカ", a: "バンギ", region: "africa" },
    { q: "赤道ギニア", a: "マラボ", region: "africa" },
    { q: "ガボン", a: "リーブルビル", region: "africa" },
    { q: "コンゴ共和国", a: "ブラザビル", region: "africa" },
    { q: "コンゴ民主共和国", a: "キンシャサ", region: "africa" },
    { q: "サントメ・プリンシペ", a: "サントメ", region: "africa" },
    { q: "ルワンダ", a: "キガリ", region: "africa" },
    { q: "ブルンジ", a: "ギテガ", region: "africa" },
    { q: "ウガンダ", a: "カンパラ", region: "africa" },
    { q: "ケニア", a: "ナイロビ", region: "africa" },
    { q: "タンザニア", a: "ドドマ", region: "africa" },
    { q: "アンゴラ", a: "ルアンダ", region: "africa" },
    { q: "ザンビア", a: "ルサカ", region: "africa" },
    { q: "マラウイ", a: "リロングウェ", region: "africa" },
    { q: "モザンビーク", a: "マプト", region: "africa" },
    { q: "ジンバブエ", a: "ハラレ", region: "africa" },
    { q: "ボツワナ", a: "ハボローネ", region: "africa" },
    { q: "ナミビア", a: "ウィントフック", region: "africa" },
    { q: "南アフリカ", a: "プレトリア", region: "africa" },
    { q: "レソト", a: "マセル", region: "africa" },
    { q: "エスワティニ", a: "ムババーネ", region: "africa" },
    { q: "マダガスカル", a: "アンタナナリボ", region: "africa" },
    { q: "モーリシャス", a: "ポートルイス", region: "africa" },
    { q: "セーシェル", a: "ビクトリア", region: "africa" },
    { q: "コモロ", a: "モロニ", region: "africa" },
    { q: "カーボベルデ", a: "プライア", region: "africa" },

    // 【北アメリカ】
    { q: "アメリカ", a: "ワシントンD.C.", region: "north_america" },
    { q: "カナダ", a: "オタワ", region: "north_america" },
    { q: "メキシコ", a: "メキシコシティ", region: "north_america" },
    { q: "グアテマラ", a: "グアテマラシティ", region: "north_america" },
    { q: "ベリーズ", a: "ベルモパン", region: "north_america" },
    { q: "ホンジュラス", a: "テグシガルパ", region: "north_america" },
    { q: "エルサルバドル", a: "サンサルバドル", region: "north_america" },
    { q: "ニカラグア", a: "マナグア", region: "north_america" },
    { q: "コスタリカ", a: "サンホセ", region: "north_america" },
    { q: "パナマ", a: "パナマシティ", region: "north_america" },
    { q: "キューバ", a: "ハバナ", region: "north_america" },
    { q: "ジャマイカ", a: "キングストン", region: "north_america" },
    { q: "ハイチ", a: "ポルトープランス", region: "north_america" },
    { q: "ドミニカ共和国", a: "サントドミンゴ", region: "north_america" },
    { q: "バハマ", a: "ナッソー", region: "north_america" },
    { q: "アンティグア・バーブーダ", a: "セントジョンズ", region: "north_america" },
    { q: "セントクリストファー・ネイビス", a: "バセテール", region: "north_america" },
    { q: "ドミニカ国", a: "ロゾー", region: "north_america" },
    { q: "セントルシア", a: "カストリーズ", region: "north_america" },
    { q: "セントビンセント・グレナディーン", a: "キングスタウン", region: "north_america" },
    { q: "バルバドス", a: "ブリッジタウン", region: "north_america" },
    { q: "グレナダ", a: "セントジョージズ", region: "north_america" },
    { q: "トリニダード・トバゴ", a: "ポートオブスペイン", region: "north_america" },

    // 【南アメリカ】
    { q: "コロンビア", a: "ボゴタ", region: "south_america" },
    { q: "ベネズエラ", a: "カラカス", region: "south_america" },
    { q: "ガイアナ", a: "ジョージタウン", region: "south_america" },
    { q: "スリナム", a: "パラマリボ", region: "south_america" },
    { q: "エクアドル", a: "キト", region: "south_america" },
    { q: "ペルー", a: "リマ", region: "south_america" },
    { q: "ブラジル", a: "ブラジリア", region: "south_america" },
    { q: "ボリビア", a: "スクレ（事実上ラパス）", region: "south_america" },
    { q: "パラグアイ", a: "アスンシオン", region: "south_america" },
    { q: "チリ", a: "サンティアゴ", region: "south_america" },
    { q: "アルゼンチン", a: "ブエノスアイレス", region: "south_america" },
    { q: "ウルグアイ", a: "モンテビデオ", region: "south_america" },

    // 【オセアニア】
    { q: "オーストラリア", a: "キャンベラ", region: "oceania" },
    { q: "ニュージーランド", a: "ウェリントン", region: "oceania" },
    { q: "パプアニューギニア", a: "ポートモレスビー", region: "oceania" },
    { q: "ソロモン諸島", a: "ホニアラ", region: "oceania" },
    { q: "バヌアツ", a: "ポートビラ", region: "oceania" },
    { q: "フィジー", a: "スバ", region: "oceania" },
    { q: "パラオ", a: "マルキョク", region: "oceania" },
    { q: "ミクロネシア連邦", a: "パリキール", region: "oceania" },
    { q: "マーシャル諸島", a: "マジュロ", region: "oceania" },
    { q: "ナウル", a: "ヤレン（事実上の首都）", region: "oceania" },
    { q: "キリバス", a: "タラワ", region: "oceania" },
    { q: "ツバル", a: "フナフティ", region: "oceania" },
    { q: "サモア", a: "アピア", region: "oceania" },
    { q: "トンガ", a: "ヌクアロファ", region: "oceania" },
    { q: "クック諸島", a: "アバルア", region: "oceania" },
    { q: "ニウエ", a: "アロフィ", region: "oceania" }
];
// 🌟 元素記号（ローマ字）から名前を当てるデータ（1〜10番）
const elementSymbolData = [
    { q: "H", a: "水素" },
    { q: "He", a: "ヘリウム" },
    { q: "Li", a: "リチウム" },
    { q: "Be", a: "ベリリウム" },
    { q: "B", a: "ホウ素" },
    { q: "C", a: "炭素" },
    { q: "N", a: "窒素" },
    { q: "O", a: "酸素" },
    { q: "F", a: "フッ素" },
    { q: "Ne", a: "ネオン" },
　　{ q: "Na", a: "ナトリウム" },
    { q: "Mg", a: "マグネシウム" },
    { q: "Al", a: "アルミニウム" },
    { q: "Si", a: "ケイ素" },
    { q: "P", a: "リン" },
    { q: "S", a: "硫黄" },
    { q: "Cl", a: "塩素" },
    { q: "Ar", a: "アルゴン" },
    { q: "K", a: "カリウム" },
    { q: "Ca", a: "カルシウム" },
    { q: "Sc", a: "スカンジウム" },
    { q: "Ti", a: "チタン" },
    { q: "V", a: "バナジウム" },
    { q: "Cr", a: "クロム" },
    { q: "Mn", a: "マンガン" },
    { q: "Fe", a: "鉄" },
    { q: "Co", a: "コバルト" },
    { q: "Ni", a: "ニッケル" },
    { q: "Cu", a: "銅" },
    { q: "Zn", a: "亜鉛" },
    { q: "Ga", a: "ガリウム" },
    { q: "Ge", a: "ゲルマニウム" },
    { q: "As", a: "ヒ素" },
    { q: "Se", a: "セレン" },
    { q: "Br", a: "臭素" },
    { q: "Kr", a: "クリプトン" },
    { q: "Rb", a: "ルビジウム" },
    { q: "Sr", a: "ストロンチウム" },
    { q: "Y", a: "イットリウム" },
    { q: "Zr", a: "ジルコニウム" },
    { q: "Nb", a: "ニオブ" },
    { q: "Mo", a: "モリブデン" },
    { q: "Tc", a: "テクネチウム" },
    { q: "Ru", a: "ルテニウム" },
    { q: "Rh", a: "ロジウム" },
    { q: "Pd", a: "パラジウム" },
    { q: "Ag", a: "銀" },
    { q: "Cd", a: "カドミウム" },
    { q: "In", a: "インジウム" },
    { q: "Sn", a: "スズ" },
    { q: "Sb", a: "アンチモン" },
    { q: "Te", a: "テルル" },
    { q: "I", a: "ヨウ素" },
    { q: "Xe", a: "キセノン" },
    { q: "Cs", a: "セシウム" },
    { q: "Ba", a: "バリウム" },
    { q: "La", a: "ランタン" },
    { q: "Ce", a: "セリウム" },
    { q: "Pr", a: "プラセオジム" },
    { q: "Nd", a: "ネオジム" },
  　{ q: "Pm", a: "プロメチウム" },
    { q: "Sm", a: "サマリウム" },
    { q: "Eu", a: "ユウロピウム" },
    { q: "Gd", a: "ガドリニウム" },
    { q: "Tb", a: "テルビウム" },
    { q: "Dy", a: "ジスプロシウム" },
    { q: "Ho", a: "ホルミウム" },
    { q: "Er", a: "エルビウム" },
    { q: "Tm", a: "ツリウム" },
    { q: "Yb", a: "イッテルビウム" },
    { q: "Lu", a: "ルテチウム" },
    { q: "Hf", a: "ハフニウム" },
    { q: "Ta", a: "タンタル" },
    { q: "W", a: "タングステン" },
    { q: "Re", a: "レニウム" },
    { q: "Os", a: "オスミウム" },
    { q: "Ir", a: "イリジウム" },
    { q: "Pt", a: "白金" },
    { q: "Au", a: "金" },
    { q: "Hg", a: "水銀" },
    { q: "Tl", a: "タリウム" },
    { q: "Pb", a: "鉛" },
    { q: "Bi", a: "ビスマス" },
    { q: "Po", a: "ポロニウム" },
    { q: "At", a: "アスタチン" },
    { q: "Rn", a: "ラドン" },
    { q: "Fr", a: "フランシウム" },
    { q: "Ra", a: "ラジウム" },
    { q: "Ac", a: "アクチニウム" },
    { q: "Th", a: "トリウム" },
    { q: "Pa", a: "プロトアクチニウム" },
    { q: "U", a: "ウラン" },
    { q: "Np", a: "ネプツニウム" },
    { q: "Pu", a: "プルトニウム" },
    { q: "Am", a: "アメリシウム" },
    { q: "Cm", a: "キュリウム" },
    { q: "Bk", a: "バークリウム" },
    { q: "Cf", a: "カリホルニウム" },
    { q: "Es", a: "アインスタイニウム" },
    { q: "Fm", a: "フェルミウム" },
    { q: "Md", a: "メンデレビウム" },
    { q: "No", a: "ノーベリウム" },
    { q: "Lr", a: "ローレンシウム" },
    { q: "Rf", a: "ラザホージウム" },
    { q: "Db", a: "ドブニウム" },
    { q: "Sg", a: "シーボーギウム" },
    { q: "Bh", a: "ボーリウム" },
    { q: "Hs", a: "ハッシウム" },
    { q: "Mt", a: "マイトネリウム" },
    { q: "Ds", a: "ダームスタチウム" },
    { q: "Rg", a: "レントゲニウム" },
    { q: "Cn", a: "コペルニシウム" },
    { q: "Nh", a: "ニホニウム" },
    { q: "Fl", a: "フレロビウム" },
    { q: "Mc", a: "モスコビウム" },
    { q: "Lv", a: "リバモリウム" },
    { q: "Ts", a: "テネシン" },
    { q: "Og", a: "オガネソン" }
];
// ペンギン全18種類データ
const penguinData = [
    { q: "ペンギンの写真", a: "エンペラーペンギン", img: "https://commons.wikimedia.org/wiki/Special:FilePath/Emperor_Penguin_Walking_on_the_Snow_in_Antarctica.jpg?width=320" },
    { q: "ペンギンの写真", a: "キングペンギン", img: "https://commons.wikimedia.org/wiki/Special:FilePath/King_Penguin_walking_on_a_beach_in_South_Georgia.jpg?width=320" },
    { q: "ペンギンの写真", a: "アデリーペンギン", img: "https://commons.wikimedia.org/wiki/Special:FilePath/Adélie_Penguin_on_the_iceberg.jpg?width=320" },
    { q: "ペンギンの写真", a: "ジェンツーペンギン", img: "https://commons.wikimedia.org/wiki/Special:FilePath/Pygoscelis_papua_(Petermann_Island_-_2012).jpg?width=320" },
    { q: "ペンギンの写真", a: "ヒゲペンギン", img: "https://commons.wikimedia.org/wiki/Special:FilePath/Pygoscelis_antarctica_(South_Shetland_Islands_-_2012).jpg?width=320" },
    { q: "ペンギンの写真", a: "マカロニペンギン", img: "https://commons.wikimedia.org/wiki/Special:FilePath/Eudyptes_chrysolophus.jpg?width=320" },
    { q: "ペンギンの写真", a: "イワトビペンギン", img: "https://commons.wikimedia.org/wiki/Special:FilePath/Eudyptes_chrysocome.jpg?width=320" },
    { q: "ペンギンの写真", a: "フィヨルドランドペンギン", img: "https://commons.wikimedia.org/wiki/Special:FilePath/Eudyptes_pachyrhynchus.jpg?width=320" },
    { q: "ペンギンの写真", a: "スネアーズペンギン", img: "https://commons.wikimedia.org/wiki/Special:FilePath/Eudyptes_robustus.jpg?width=320" },
    { q: "ペンギンの写真", a: "シュレーターペンギン", img: "https://commons.wikimedia.org/wiki/Special:FilePath/Eudyptes_sclateri.jpg?width=320" },
    { q: "ペンギンの写真", a: "ロイヤルペンギン", img: "https://commons.wikimedia.org/wiki/Special:FilePath/Eudyptes_schlegeli.jpg?width=320" },
    { q: "ペンギンの写真", a: "キガシラペンギン", img: "https://commons.wikimedia.org/wiki/Special:FilePath/Megadyptes_antipodes.jpg?width=320" },
    { q: "ペンギンの写真", a: "ケープペンギン", img: "https://commons.wikimedia.org/wiki/Special:FilePath/Spheniscus_demersus.jpg?width=320" },
    { q: "ペンギンの写真", a: "マゼランペンギン", img: "https://commons.wikimedia.org/wiki/Special:FilePath/Spheniscus_magellanicus.jpg?width=320" },
    { q: "ペンギンの写真", a: "フンボルトペンギン", img: "https://commons.wikimedia.org/wiki/Special:FilePath/Spheniscus_humboldti.jpg?width=320" },
    { q: "ペンギンの写真", a: "ガラパゴスペンギン", img: "https://commons.wikimedia.org/wiki/Special:FilePath/Spheniscus_mendiculus.jpg?width=320" },
    { q: "ペンギンの写真", a: "コガタペンギン", img: "https://commons.wikimedia.org/wiki/Special:FilePath/Eudyptula_minor.jpg?width=320" },
    { q: "ペンギンの写真", a: "ハネジロペンギン", img: "https://commons.wikimedia.org/wiki/Special:FilePath/Eudyptula_albosignata.jpg?width=320" }
];
